default: &default
  adapter: postgresql
  encoding: unicode
  username: elizabeth
  password: 123456
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: onebitflix_development